server:
  port: 8012

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

spring:
  application:
    name: edumark-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edumark
    username: root
    password: 123456

  initialize: false
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
# logger
logging:
  level:
    root: INFO
    org:
      hibernate: INFO

